name: Continuous FFmpeg Stream to Facebook Live

on:
  push:
    branches:
      - main  # أو أي فرع تود تشغيله عليه

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Start continuous stream to Facebook Live
      run: |
        m3u8_link="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"
        stream_key="FB-559234810181379-0-AbyQLvN7H1kn07u4"
        output_url="rtmps://live-api-s.facebook.com:443/rtmp/$stream_key"

        # تشغيل البث في الخلفية باستخدام nohup
        nohup ffmpeg -i "$m3u8_link" \
          -c:v libx264 \
          -preset fast \
          -b:v 3000k \
          -maxrate 3000k \
          -bufsize 6000k \
          -s 1920x1080 \
          -c:a aac \
          -b:a 128k \
          -f flv "$output_url" &

        # التأكد من أن العملية تعمل في الخلفية
        ps aux | grep ffmpeg
