name: Facebook Live Streaming in 4K

on:
  push:
    branches:
      - main

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    - name: Run FFmpeg for 4K Facebook Streaming
      run: |
        m3u8_link="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"
        stream_key="FB-559223543515839-0-AbyS-GVN_fkHZNZV"
        output_url="rtmps://live-api-s.facebook.com:443/rtmp/$stream_key"
        
        # إعدادات بث 4K
        ffmpeg -i "$m3u8_link" \
          -c:v libx264 \
          -preset fast \
          -b:v 6000k \  # تحديد معدل البت للبث بدقة 4K
          -maxrate 6000k \  # تحديد أقصى معدل للبت
          -bufsize 12000k \  # تحديد حجم المخزن المؤقت (buffer size)
          -s 3840x2160 \  # تعيين الدقة إلى 4K (3840x2160)
          -c:a aac \
          -b:a 192k \  # إعدادات الصوت
          -f flv "$output_url" &  # تحديد بروتوكول الفيدو RTMP لإرسال البث إلى فيسبوك

        echo "4K Streaming started..."
