name: Facebook Live Streaming

on:
  push:
    branches:
      - main

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    - name: Run FFmpeg for Facebook Streaming
      run: |
        m3u8_link="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"
        stream_key="FB-559223543515839-0-AbyS-GVN_fkHZNZV"
        output_url="rtmps://live-api-s.facebook.com:443/rtmp/$stream_key"
        
        # Run FFmpeg to start streaming
        nohup ffmpeg -i "$m3u8_link" -c:v libx264 -preset fast -b:v 3000k -c:a aac -b:a 128k -f flv "$output_url" &
        
        echo "Streaming started..."
