name: Facebook Live Streaming in 1080p

on:
  push:
    branches:
      - main

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    - name: Run FFmpeg for 1080p Facebook Streaming
      run: |
        m3u8_link="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"
        stream_key="FB-559223543515839-0-AbyS-GVN_fkHZNZV"
        output_url="rtmps://live-api-s.facebook.com:443/rtmp/$stream_key"
        
        # إعدادات بث 1080p
        ffmpeg -i "$m3u8_link" \
          -c:v libx264 \
          -preset fast \
          -b:v 3000k \  # تحديد معدل البت للبث بدقة 1080p
          -maxrate 3000k \  # تحديد أقصى معدل للبت
          -bufsize 6000k \  # تحديد حجم المخزن المؤقت (buffer size)
          -s 1920x1080 \  # تعيين الدقة إلى 1080p (1920x1080)
          -c:a aac \
          -b:a 128k \  # إعدادات الصوت
          -f flv "$output_url" &  # تحديد بروتوكول الفيدو RTMP لإرسال البث إلى فيسبوك

        echo "1080p Streaming started..."
