name: Live Stream to Facebook

on:
  push:
    branches:
      - main

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Start Live Stream
        run: |
          m3u8_link="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"
          stream_key="FB-559223543515839-0-AbyS-GVN_fkHZNZV"
          output_url="rtmps://live-api-s.facebook.com:443/rtmp/$stream_key"
          
          ffmpeg -i "$m3u8_link" \
            -c:v libx264 \
            -preset fast \
            -b:v 3000k \  # 1080p Bitrate
            -maxrate 3000k \
            -bufsize 6000k \
            -s 1920x1080 \  # 1080p Resolution
            -c:a aac \
            -b:a 128k \  # Audio Bitrate
            -f flv "$output_url"  # RTMP Output to Facebook
