rtname: Continuous FFmpeg Stream to Facebook iLive

on:
  push:
    branches:
      - main  # أو أي فرع تود تشغيله عليه

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Start continuous stream to Facebook Live
      run: |
        m3u8_link="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"
        stream_key="FB-559264340178426-0-AbwP7R93-TPB3Ank"
        output_url="rtmps://live-api-s.facebook.com:443/rtmp/$stream_key"

        # إضافة سجلات للمساعدة في تتبع الأخطاء
        echo "Starting FFmpeg stream to Facebook Live..."
        echo "Input Stream URL: $m3u8_link"
        echo "Output Stream URL: $output_url"

        # تشغيل FFmpeg في الخلفية باستخدام nohup لضمان استمرار العملية
        nohup ffmpeg -i "$m3u8_link" \
          -c:v libx264 \
          -preset fast \
          -b:v 3000k \
          -maxrate 3000k \
          -bufsize 6000k \
          -s 1920x1080 \
          -c:a aac \
          -b:a 128k \
          -f flv "$output_url" > ffmpeg_output.log 2>&1 &

        # التأكد من أن العملية تعمل في الخلفية
        sleep 5  # تأخير بسيط للتأكد من بدء العملية
        if ps aux | grep "[f]fmpeg"; then
          echo "FFmpeg is running successfully in the background."
        else
          echo "Error: FFmpeg process did not start correctly."
          exit 1  # إيقاف التشغيل إذا كانت العملية فاشلة
        fi

        # إظهار السجلات لتتبع حالة البث
        tail -f ffmpeg_output.log
