name: Facebook Live Stream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # تشغيل كل ساعة

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Setup FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Start Streaming
      run: |
        STREAM_KEY="FB-560151130089747-0-AbzOS9BPghfmXtZb"
        M3U8_URL="https://live4.beinconnect.us/YallaGoalApp/beINSports3.m3u8"
        ffmpeg -re -i "$M3U8_URL" \
        -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
        -pix_fmt yuv420p -c:a aac -b:a 128k -ar 44100 \
        -f flv "rtmp://live-api-s.facebook.com:80/rtmp/$STREAM_KEY"
